<a href="https://colab.research.google.com/github/Nagaraj-1234-lang/Experiment-1-Matrix/blob/main/ML_Experiment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Experiment 1
import numpy as np
A= np.array([[5.0, 1.0], [7.0,2.0]])
B= np.array([1.0, 2.0])
print("Matrix A:\n", A)
print("\nTranspose A^T:\n",A.T)
print("\nInverse A^-1:\n",np.linalg.inv(A))
eigvals, eigvecs = np.linalg.eig(A)
print ("\nEigenvalues:", np.round(eigvals,4))
x= np.linalg.solve(A,B)
print("\nSolve A x = B --> x:", np.round(x,4))

Matrix A:
 [[5. 1.]
 [7. 2.]]

Transpose A^T:
 [[5. 7.]
 [1. 2.]]

Inverse A^-1:
 [[ 0.66666667 -0.33333333]
 [-2.33333333  1.66666667]]

Eigenvalues: [6.5414 0.4586]

Solve A x = B --> x: [0. 1.]
